name = "MyRegistry"
uuid = "32ba9c01-19eb-4a2c-aa64-d66783ff8cbf"
repo = "https://github.com/andresegido/MyRegistry"
description = "A small registry for my Julia packages"

[packages]
30fbeecf-ffb7-46dc-b478-c8da4eefd92c = { name = "IdealGas", path = "I/IdealGas" }
42ba331d-5cb5-46e2-ab3c-303811c0b0ef = { name = "AeroGrid", path = "A/AeroGrid" }
b9ad882a-eaba-4331-a7f2-de70c89f50e3 = { name = "UVLM", path = "U/UVLM" }
