name = "MyRegistry"
uuid = "32ba9c01-19eb-4a2c-aa64-d66783ff8cbf"
repo = "https://github.com/andresegido/MyRegistry"
description = "A small registry for my Julia packages"

[packages]
30fbeecf-ffb7-46dc-b478-c8da4eefd92c = { name = "IdealGas", path = "I/IdealGas" }
6bad4d00-7c4f-4689-8ad1-81d3c0b2abd8 = { name = "Atmosphere", path = "A/Atmosphere" }
